#!/bin/bash

python parser/GraphML-Topo-to-Mininet-Network-Generator.py -f parser/topologies/Abilene.graphml -c 10.0.3.11
rm -rf /tmp/ITGRecv-Logs
mkdir /tmp/ITGRecv-Logs
sudo mn -c
sudo pkill ITG
sudo pkill sshd
sudo python parser/topologies/Abilene.graphml-generated-Mininet-Topo.py 

